FROM --platform=x86_64 ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    cmake \
    build-essential \
    libgoogle-glog-dev \
    libgflags-dev \
    libatlas-base-dev \
    libeigen3-dev \
    curl

# Install ceres-solver
RUN curl http://ceres-solver.org/ceres-solver-2.2.0.tar.gz | tar -xz \
    && cd ceres-solver-2.2.0 \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make -j$(nproc) \
    && make install \
    && cd ../.. \
    && rm -rf ceres-solver-2.2.0