FROM --platform=x86_64 ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    cmake \
    build-essential \
    libgoogle-glog-dev \
    libgflags-dev \
    libatlas-base-dev \
    libeigen3-dev \
    curl \
    libsuitesparse-dev

RUN apt-get install libceres-dev -y

# Install ceres-solver
COPY pose_graph_3d /pose_graph_3d

RUN mkdir posegraph-bin \
    && cd posegraph-bin \
    && cmake ../pose_graph_3d \
    && make -j$(nproc) \
    && mv pose_graph_3d /usr/local/bin \
    && cd .. \
    && rm -rf posegraph-bin pose_graph_3d

CMD ["bash"]